# Generated by Django 4.2.28 on 2026-02-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question_type',
            field=models.CharField(choices=[('standard', 'Standard Q&A'), ('multiple_choice', 'Multiple Choice'), ('step_by_step', 'Step-by-Step Problem')], default='standard', help_text='Type of question presentation', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Topics that should be mastered before this one', related_name='required_for', to='study.topic'),
        ),
        migrations.CreateModel(
            name='MultipleChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('flashcard', models.ForeignKey(limit_choices_to={'question_type': 'multiple_choice'}, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='study.flashcard')),
            ],
            options={
                'ordering': ['flashcard', 'order'],
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Foundational skills required for this question', related_name='flashcards', to='study.skill'),
        ),
    ]
