# Generated by Django 4.2.28 on 2026-02-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_skill_flashcard_question_type_topic_prerequisites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='answer_template',
            field=models.TextField(blank=True, help_text='Template with {variable} placeholders for the answer'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='parameter_spec',
            field=models.JSONField(blank=True, help_text='JSON specification of parameters, ranges, and computations', null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question_template',
            field=models.TextField(blank=True, help_text="Template with {variable} placeholders. Used when question_type='parameterized'"),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question_type',
            field=models.CharField(choices=[('standard', 'Standard Q&A'), ('multiple_choice', 'Multiple Choice'), ('step_by_step', 'Step-by-Step Problem'), ('parameterized', 'Parameterized/Randomized')], default='standard', help_text='Type of question presentation', max_length=20),
        ),
    ]
