# Generated by Django 4.2.28 on 2026-02-13 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_flashcard_answer_template_flashcard_parameter_spec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(help_text='Category: math, circuit, programming, etc.', max_length=50)),
                ('default_config', models.JSONField(help_text='Default settings for this template')),
                ('example_image', models.ImageField(blank=True, null=True, upload_to='templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='code_language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('c', 'C'), ('cpp', 'C++'), ('matlab', 'MATLAB'), ('vhdl', 'VHDL'), ('javascript', 'JavaScript')], max_length=20),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='code_snippet',
            field=models.TextField(blank=True, help_text='Code snippet to display'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='diagram_code',
            field=models.TextField(blank=True, help_text='Mermaid.js diagram code'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='diagram_type',
            field=models.CharField(choices=[('none', 'No Diagram'), ('flowchart', 'Flowchart'), ('sequence', 'Sequence Diagram'), ('class', 'Class Diagram'), ('state', 'State Diagram'), ('gantt', 'Gantt Chart'), ('mindmap', 'Mind Map'), ('pie', 'Pie Chart'), ('git', 'Git Graph')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='generated_graph_image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_graphs/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='graph_code',
            field=models.TextField(blank=True, help_text='Python code to generate graph using matplotlib'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='graph_config',
            field=models.JSONField(blank=True, help_text='Graph configuration (title, labels, range, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='graph_type',
            field=models.CharField(choices=[('none', 'No Graph'), ('function', 'Function Plot'), ('parametric', 'Parametric Plot'), ('3d', '3D Surface Plot'), ('vector', 'Vector Field')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='uses_latex',
            field=models.BooleanField(default=False, help_text='Check if this card contains LaTeX equations'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used to create this card', null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.cardtemplate'),
        ),
    ]
