# Generated by Django 4.2.28 on 2026-02-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_flashcard_answer_template_flashcard_parameter_spec_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
