# Generated by Django 4.2.28 on 2026-02-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_cardfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcards/answers/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcards/questions/'),
        ),
    ]
