# Generated by Django 4.2.28 on 2026-02-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_cardtemplate_flashcard_code_language_and_more'),
        ('study', '0006_flashcard_answer_image_flashcard_question_image'),
    ]

    operations = [
    ]
