# Generated by Django 4.2.28 on 2026-02-17 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0008_courseenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_mode', models.CharField(choices=[('standard', 'Standard'), ('visual', 'Visual (emphasis on diagrams and images)'), ('text_heavy', 'Text Heavy (focus on text content)'), ('challenge', 'Challenge (timed, no hints)')], default='standard', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
