# Generated by Django 4.2.28 on 2026-02-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_studypreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardFeedback',
        ),
    ]
