# Generated by Django 4.2.28 on 2026-02-24 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import study.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0010_remove_cardfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountabilityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=study.models.generate_accountability_code, max_length=10, unique=True)),
                ('label', models.CharField(blank=True, help_text='Optional label (e.g., "Teacher", "Study Group")', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountability_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_cards', models.IntegerField(default=0, help_text='Target cards per day (0 = no goal)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_slug', models.CharField(max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['earned_at'],
                'unique_together': {('user', 'badge_slug')},
            },
        ),
        migrations.CreateModel(
            name='AccountabilityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observers', to='study.accountabilitylink')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('observer', 'link')},
            },
        ),
    ]
