# Generated by Django 4.2.28 on 2026-02-24 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0011_add_accountability_and_badges'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flashcardprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='steps',
            field=models.JSONField(blank=True, help_text='Ordered solution steps for step_by_step cards. List of {"move": "action label", "detail": "full working"}', null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='teacher_explanation',
            field=models.TextField(blank=True, help_text='Full worked explanation written as a teacher would give it. Shown only on user request. Include reasoning and common mistakes.'),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='step_index',
            field=models.IntegerField(default=-1, help_text='-1 = whole card; 0..N-1 = individual step index for step_by_step cards'),
        ),
        migrations.AlterUniqueTogether(
            name='flashcardprogress',
            unique_together={('user', 'flashcard', 'step_index')},
        ),
        migrations.CreateModel(
            name='TopicScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='0.0-1.0 rolling average confidence')),
                ('attempt_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='study.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
