# Generated by Django 4.2.28 on 2026-02-26 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0027_set_topic_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['course', 'code', 'name']},
        ),
        migrations.AlterField(
            model_name='flashcardprogress',
            name='step_index',
            field=models.IntegerField(default=-1, help_text='-1 = whole card; 0..N-1 = individual step index for step_by_step cards', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='topicscore',
            name='score',
            field=models.FloatField(default=0.0, help_text='0.0-1.0 rolling average confidence', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
