# Generated by Django 4.2.29 on 2026-03-06 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0032_add_flashcard_vote_and_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardcomment',
            name='body',
            field=models.TextField(help_text='Comment or suggested improvement', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
