# Generated by Django 4.2.29 on 2026-03-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0033_alter_flashcardcomment_body_add_validator'),
        ('study', '0035_flashcards_sma212'),
    ]

    operations = [
    ]
