# Generated by Django 4.2.29 on 2026-03-06 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0036_merge_20260306_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='aqf_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 1 — Primary (Year 1)'), (2, 'Level 2 — Primary (Year 2)'), (3, 'Level 3 — Primary (Year 3)'), (4, 'Level 4 — Primary (Year 4)'), (5, 'Level 5 — Primary (Year 5)'), (6, 'Level 6 — Primary (Year 6)'), (7, 'Level 7 — Junior Secondary (Year 7)'), (8, 'Level 8 — Junior Secondary (Year 8)'), (9, 'Level 9 — Junior Secondary (Year 9)'), (10, 'Level 10 — Junior Secondary (Year 10)'), (11, 'Level 11 — Senior Secondary (Year 11)'), (12, 'Level 12 — Senior Secondary (Year 12)'), (13, 'Level 13 — AQF 1 (Certificate I)'), (14, 'Level 14 — AQF 2 (Certificate II)'), (15, 'Level 15 — AQF 3 (Certificate III)'), (16, 'Level 16 — AQF 4 (Certificate IV)'), (17, 'Level 17 — AQF 5 (Diploma)'), (18, 'Level 18 — AQF 6 (Associate Degree / Advanced Diploma)'), (19, 'Level 19 — AQF 7 (Bachelor)'), (20, 'Level 20 — AQF 8–10 (Honours / Masters / Doctorate)')], help_text='AQF-aligned difficulty level (1 = Year 1 primary, 20 = Honours/Masters/Doctorate)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='star_difficulty',
            field=models.IntegerField(blank=True, choices=[(1, '★☆☆☆☆☆ — Entry-level concept'), (2, '★★☆☆☆☆ — Foundational'), (3, '★★★☆☆☆ — Moderate'), (4, '★★★★☆☆ — Challenging'), (5, '★★★★★☆ — Advanced'), (6, '★★★★★★ — Most advanced')], help_text='Relative difficulty within the subject (1 = easiest, 6 = hardest). If blank, inherits from the topic.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='topic',
            name='aqf_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 1 — Primary (Year 1)'), (2, 'Level 2 — Primary (Year 2)'), (3, 'Level 3 — Primary (Year 3)'), (4, 'Level 4 — Primary (Year 4)'), (5, 'Level 5 — Primary (Year 5)'), (6, 'Level 6 — Primary (Year 6)'), (7, 'Level 7 — Junior Secondary (Year 7)'), (8, 'Level 8 — Junior Secondary (Year 8)'), (9, 'Level 9 — Junior Secondary (Year 9)'), (10, 'Level 10 — Junior Secondary (Year 10)'), (11, 'Level 11 — Senior Secondary (Year 11)'), (12, 'Level 12 — Senior Secondary (Year 12)'), (13, 'Level 13 — AQF 1 (Certificate I)'), (14, 'Level 14 — AQF 2 (Certificate II)'), (15, 'Level 15 — AQF 3 (Certificate III)'), (16, 'Level 16 — AQF 4 (Certificate IV)'), (17, 'Level 17 — AQF 5 (Diploma)'), (18, 'Level 18 — AQF 6 (Associate Degree / Advanced Diploma)'), (19, 'Level 19 — AQF 7 (Bachelor)'), (20, 'Level 20 — AQF 8–10 (Honours / Masters / Doctorate)')], help_text='AQF-aligned difficulty level. If blank, inherits from the course.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='topic',
            name='star_difficulty',
            field=models.IntegerField(blank=True, choices=[(1, '★☆☆☆☆☆ — Entry-level concept'), (2, '★★☆☆☆☆ — Foundational'), (3, '★★★☆☆☆ — Moderate'), (4, '★★★★☆☆ — Challenging'), (5, '★★★★★☆ — Advanced'), (6, '★★★★★★ — Most advanced')], help_text='Relative difficulty within the subject (1 = easiest, 6 = hardest)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
