# Generated by Django 4.2.29 on 2026-03-06 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0037_add_aqf_level_and_star_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question or front of the suggested card')),
                ('answer', models.TextField(help_text='Answer or back of the suggested card')),
                ('hint', models.TextField(blank=True, help_text='Optional hint')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from the reviewer (not shown to the submitter)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_suggestions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_suggestions', to='study.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
