# Generated by Django 4.2.29 on 2026-03-06 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0038_add_card_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsuggestion',
            name='answer',
            field=models.TextField(help_text='Answer or back of the suggested card', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='cardsuggestion',
            name='hint',
            field=models.TextField(blank=True, help_text='Optional hint', validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='cardsuggestion',
            name='question',
            field=models.TextField(help_text='Question or front of the suggested card', validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
