# Generated by Django 4.2.29 on 2026-03-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0033_analog_electronics_missing_topics'),
        ('study', '0039_add_cardsuggestion_validators'),
    ]

    operations = [
    ]
