# Generated by Django 6.0.3 on 2026-03-12 21:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0040_merge_20260309_1337'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardprogress',
            name='easiness_factor',
            field=models.FloatField(default=2.5, help_text='SM-2 easiness factor (≥1.3). Higher = longer intervals between reviews.', validators=[django.core.validators.MinValueValidator(1.3)]),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='interval_days',
            field=models.IntegerField(default=0, help_text='Current interval in days (0 = new card, never reviewed via SM-2).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='next_review_date',
            field=models.DateField(blank=True, help_text='Date this card is next due for review. Null means the card is new.', null=True),
        ),
        migrations.AddField(
            model_name='flashcardprogress',
            name='sm2_repetitions',
            field=models.IntegerField(default=0, help_text='Consecutive successful SM-2 recalls (resets to 0 on failure).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='SpacedRepetitionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_modifier', models.IntegerField(choices=[(-2, 'Much slower — review cards very frequently'), (-1, 'Slower — more frequent reviews'), (0, 'Normal — standard SM-2 schedule'), (1, 'Faster — longer gaps between reviews'), (2, 'Much faster — aggressive spacing')], default=0, help_text='Shifts how quickly review intervals grow. Increase if you remember things faster than average; decrease if slower.', validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)])),
                ('max_interval_days', models.IntegerField(default=365, help_text='Maximum days between reviews (30–730). Cap prevents intervals from growing too large.', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(730)])),
                ('daily_new_cards', models.IntegerField(default=20, help_text='Maximum new (never reviewed) cards to introduce per review session (1–100).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sr_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
