# Generated by Django 4.2.29 on 2026-03-12 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0041_spaced_repetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardprogress',
            name='easiness_factor',
            field=models.FloatField(default=2.5, help_text='SM-2 easiness factor (≥1.1). Higher = longer intervals between reviews.', validators=[django.core.validators.MinValueValidator(1.1)]),
        ),
    ]
